[
  { "id": 1, "Nombre": "Cheeseburger", "Precio": 5990, "Activo": true },
  { "id": 2, "Nombre": "Hamburguesa Chacarera", "Precio": 6990, "Activo": true },
  { "id": 3, "Nombre": "Hamburguesa Gringa", "Precio": 6990, "Activo": true },
  { "id": 4, "Nombre": "Hamburguesa Italiana", "Precio": 6990, "Activo": true },
  { "id": 5, "Nombre": "Wistuburguer", "Precio": 7990, "Activo": true },
  { "id": 6, "Nombre": "Chorrillana Cerdo", "Precio": 10990, "Activo": true },
  { "id": 7, "Nombre": "Chorrillana Pollo", "Precio": 10990, "Activo": true },
  { "id": 8, "Nombre": "Chorrillana Vacuno", "Precio": 10990, "Activo": true },
  { "id": 9, "Nombre": "Chorrillana todas las carnes", "Precio": 11990, "Activo": true },
  { "id": 10, "Nombre": "Chorrillana pichanga", "Precio": 12990, "Activo": true },
  { "id": 11, "Nombre": "Chorrillana Mar y Tierra", "Precio": 13990, "Activo": true },
  { "id": 12, "Nombre": "Menú niños", "Precio": 5990, "Activo": true },
  { "id": 13, "Nombre": "Papas Fritas (caseras)", "Precio": 6990, "Activo": true },
  { "id": 14, "Nombre": "SALCHI papas", "Precio": 7990, "Activo": true },
  { "id": 15, "Nombre": "Papas BRAVAS", "Precio": 9990, "Activo": true },
  { "id": 16, "Nombre": "Chicken papas", "Precio": 10990, "Activo": true },
  { "id": 17, "Nombre": "Papas gringas", "Precio": 10990, "Activo": true },
  { "id": 18, "Nombre": "Papas vegetarianas", "Precio": 10990, "Activo": true },
  { "id": 19, "Nombre": "Tabla Picoteo PEQUEÑO", "Precio": 4990, "Activo": true },
  { "id": 20, "Nombre": "Tabla Picoteo MEDIANO", "Precio": 8990, "Activo": true },
  { "id": 21, "Nombre": "Tabla surtida de la Wistu", "Precio": 12990, "Activo": true },
  { "id": 22, "Nombre": "Camarones salteados", "Precio": 14990, "Activo": true },
  { "id": 23, "Nombre": "Tabla campestre Filete de costillar", "Precio": 15990, "Activo": true },
  { "id": 24, "Nombre": "Tabla chilena", "Precio": 15990, "Activo": true },
  { "id": 25, "Nombre": "Salsa queso MERKEN", "Precio": 1500, "Activo": true },
  { "id": 26, "Nombre": "Salsa de AJO", "Precio": 2000, "Activo": true },
  { "id": 27, "Nombre": "Salsa Verde", "Precio": 2000, "Activo": true },
  { "id": 28, "Nombre": "Pebre", "Precio": 2000, "Activo": true },
  { "id": 29, "Nombre": "Pizza pollo champiñón", "Precio": 10990, "Activo": true },
  { "id": 30, "Nombre": "Pizza napolitana", "Precio": 10990, "Activo": true },
  { "id": 31, "Nombre": "Pizza pepperoni", "Precio": 10990, "Activo": true },
  { "id": 32, "Nombre": "Pizza vegetariana", "Precio": 10990, "Activo": true },
  { "id": 33, "Nombre": "Pizza queso camaron", "Precio": 12990, "Activo": true },
  { "id": 34, "Nombre": "Ceviche choritos 500 gr", "Precio": 10990, "Activo": true },
  { "id": 35, "Nombre": "Ceviche Salmon 500 gr", "Precio": 11990, "Activo": true },
  { "id": 36, "Nombre": "Té", "Precio": 1990, "Activo": true },
  { "id": 37, "Nombre": "Café", "Precio": 1990, "Activo": true },
  { "id": 38, "Nombre": "Dos Schop Budweiser 500cc", "Precio": 5990, "Activo": true },
  { "id": 39, "Nombre": "Promo Pisco (dos cortos de pisco + 1 bebida)", "Precio": 6990, "Activo": true },
  { "id": 40, "Nombre": "Dos Mojitos Cubanos de 1/2 litro", "Precio": 7990, "Activo": true },
  { "id": 41, "Nombre": "Dos Mojitos de Sabor 1/2 litro", "Precio": 8990, "Activo": true },
  { "id": 42, "Nombre": "Dos Ramazzotti", "Precio": 8990, "Activo": true },
  { "id": 43, "Nombre": "Dos Aperol", "Precio": 8990, "Activo": true },
  { "id": 44, "Nombre": "Dos Electric Lemonade 450cc", "Precio": 8990, "Activo": true },
  { "id": 45, "Nombre": "Tequila x5 Promo (5 shot de tequila)", "Precio": 10000, "Activo": true },
  { "id": 46, "Nombre": "Dos Gin Tropical", "Precio": 11990, "Activo": true },
  { "id": 47, "Nombre": "Dos Gin Frutal + Pulpa", "Precio": 12990, "Activo": true },
  { "id": 48, "Nombre": "Mojito Cubano 1/2 litro", "Precio": 5500, "Activo": true },
  { "id": 49, "Nombre": "Mojito Sabores 1/2 litro", "Precio": 5990, "Activo": true },
  { "id": 50, "Nombre": "Mojito Jagger 1/2 litro", "Precio": 6500, "Activo": true },
  { "id": 51, "Nombre": "Mojito Manzana 1/2 litro", "Precio": 6500, "Activo": true },
  { "id": 52, "Nombre": "Mojito Cerveza 800cc", "Precio": 7500, "Activo": true },
  { "id": 53, "Nombre": "Mojito Cubano de 1 litro", "Precio": 7500, "Activo": true },
  { "id": 54, "Nombre": "Mojito Electric Litro", "Precio": 7990, "Activo": true },
  { "id": 55, "Nombre": "Tequila", "Precio": 2500, "Activo": true },
  { "id": 56, "Nombre": "Wistufire (shot con fuego)", "Precio": 3000, "Activo": true },
  { "id": 57, "Nombre": "Jagger", "Precio": 3500, "Activo": true },
  { "id": 58, "Nombre": "Jagger + Dick Fire", "Precio": 4000, "Activo": true },
  { "id": 59, "Nombre": "Wistulove (Ramazzotti - Pink Tonic - Gin - Frutos)", "Precio": 7000, "Activo": true },
  { "id": 60, "Nombre": "Spritz Rose (Limonade Rose - Gin Pink - Espumante - Frutas)", "Precio": 7500, "Activo": true },
  { "id": 61, "Nombre": "Base Chelada (sal - limón)", "Precio": 1000, "Activo": true },
  { "id": 62, "Nombre": "Base Michelada (limón, sal, merken)", "Precio": 1000, "Activo": true },
  { "id": 63, "Nombre": "Base Michelada Tabasco y Salsa Inglesa", "Precio": 1300, "Activo": true },
  { "id": 64, "Nombre": "Botellines 350cc", "Precio": 3000, "Activo": true },
  { "id": 65, "Nombre": "Austral Calafate", "Precio": 3500, "Activo": true },
  { "id": 66, "Nombre": "Schop Budweiser", "Precio": 3500, "Activo": true },
  { "id": 67, "Nombre": "Schop Kunstmann Torobayo", "Precio": 3990, "Activo": true },
  { "id": 68, "Nombre": "Artesanal", "Precio": 3990, "Activo": true },
  { "id": 69, "Nombre": "Gin con Gin", "Precio": 6500, "Activo": true },
  { "id": 70, "Nombre": "Gin + Pink Tonic", "Precio": 6500, "Activo": true },
  { "id": 71, "Nombre": "Gin Tonic", "Precio": 6500, "Activo": true },
  { "id": 72, "Nombre": "Gin Red Bull de Sabores", "Precio": 6990, "Activo": true },
  { "id": 73, "Nombre": "Gin Limonade Rose", "Precio": 7300, "Activo": true },
  { "id": 74, "Nombre": "Gin Frutal + Redbull (Pulpa Frutas)", "Precio": 7500, "Activo": true },
  { "id": 75, "Nombre": "Angría 1/2 Lt.", "Precio": 3500, "Activo": true },
  { "id": 76, "Nombre": "Copa de Vino (Casillero del Diablo)", "Precio": 4000, "Activo": true },
  { "id": 77, "Nombre": "Borgoña 1L", "Precio": 6500, "Activo": true },
  { "id": 78, "Nombre": "Sangría 1 Lt.", "Precio": 6500, "Activo": true },
  { "id": 79, "Nombre": "Alto del Carmen 35° + Bebida", "Precio": 4500, "Activo": true },
  { "id": 80, "Nombre": "Mistral 35° + Bebida", "Precio": 4500, "Activo": true },
  { "id": 81, "Nombre": "Jack Daniels (Fire, Manzana, N7, Honey)", "Precio": 7500, "Activo": true },
  { "id": 82, "Nombre": "Jack Daniels + Bebida", "Precio": 8500, "Activo": true },
  { "id": 83, "Nombre": "Jack Daniels + Red Bull", "Precio": 9000, "Activo": true },
  { "id": 84, "Nombre": "Johnnie Walker Red Label", "Precio": 5500, "Activo": true },
  { "id": 85, "Nombre": "Johnnie Walker Red Label + Bebida", "Precio": 6500, "Activo": true },
  { "id": 86, "Nombre": "Johnnie Walker Red Label + Red Bull", "Precio": 7000, "Activo": true },
  { "id": 87, "Nombre": "Pisco Mistral Nobel + Bebida", "Precio": 6500, "Activo": true },
  { "id": 88, "Nombre": "Vodka + Bebida", "Precio": 6000, "Activo": true },
  { "id": 89, "Nombre": "Jagger + Bebida", "Precio": 6500, "Activo": true },
  { "id": 90, "Nombre": "Jagger + Redbull", "Precio": 7000, "Activo": true },
  { "id": 91, "Nombre": "Fernet + Bebida", "Precio": 6000, "Activo": true },
  { "id": 92, "Nombre": "Agua Mineral con Gas", "Precio": 1500, "Activo": true },
  { "id": 93, "Nombre": "Agua Mineral sin Gas", "Precio": 1500, "Activo": true },
  { "id": 94, "Nombre": "Bebida 237cc", "Precio": 1990, "Activo": true },
  { "id": 95, "Nombre": "Agua Tónica", "Precio": 2500, "Activo": true },
  { "id": 96, "Nombre": "Coca Cola 350cc", "Precio": 2500, "Activo": true },
  { "id": 97, "Nombre": "Ginger Ale Nordic 350cc", "Precio": 2500, "Activo": true },
  { "id": 98, "Nombre": "Red Bull Sabores", "Precio": 2500, "Activo": true },
  { "id": 99, "Nombre": "Limonada", "Precio": 3200, "Activo": true },
  { "id": 100, "Nombre": "Jugos Naturales (Frutilla - Mango)", "Precio": 3500, "Activo": true },
  { "id": 101, "Nombre": "Limonada Menta Jengibre", "Precio": 3500, "Activo": true },
  { "id": 102, "Nombre": "Amaretto Sour", "Precio": 4000, "Activo": true },
  { "id": 103, "Nombre": "Pisco Sour Tradicional (Copa Fina)", "Precio": 4000, "Activo": true },
  { "id": 104, "Nombre": "Pisco Sour Sabores 300cc", "Precio": 5000, "Activo": true },
  { "id": 105, "Nombre": "Caipirinha", "Precio": 6000, "Activo": true },
  { "id": 106, "Nombre": "Caipiroska", "Precio": 6000, "Activo": true },
  { "id": 107, "Nombre": "Tom Collins", "Precio": 5990, "Activo": true },
  { "id": 108, "Nombre": "Negroni", "Precio": 6000, "Activo": true },
  { "id": 109, "Nombre": "Boulevardier", "Precio": 6000, "Activo": true },
  { "id": 110, "Nombre": "Ramazzotti Violetto Spritz", "Precio": 5990, "Activo": true },
  { "id": 111, "Nombre": "Aperol Spritz", "Precio": 5990, "Activo": true },
  { "id": 112, "Nombre": "Clavo Oxidado", "Precio": 6500, "Activo": true },
  { "id": 113, "Nombre": "Daikiri", "Precio": 5500, "Activo": true },
  { "id": 114, "Nombre": "Daiquiri Sabores", "Precio": 5990, "Activo": true },
  { "id": 115, "Nombre": "Electric Lemonade 500cc", "Precio": 5990, "Activo": true },
  { "id": 116, "Nombre": "John Collins", "Precio": 5990, "Activo": true },
  { "id": 117, "Nombre": "Ramazzotti Rosato Spritz", "Precio": 5990, "Activo": true },
  { "id": 118, "Nombre": "Ruso Blanco", "Precio": 5990, "Activo": true },
  { "id": 119, "Nombre": "Ruso Negro", "Precio": 4990, "Activo": true },
  { "id": 120, "Nombre": "Tequila Margarita", "Precio": 5500, "Activo": true },
  { "id": 121, "Nombre": "Tequila Margarita Sabores", "Precio": 5990, "Activo": true },
  { "id": 122, "Nombre": "Moscow Mule (Vodka)", "Precio": 6000, "Activo": true },
  { "id": 123, "Nombre": "London Mule (Gin)", "Precio": 6500, "Activo": true },
  { "id": 124, "Nombre": "Botellin 350cc sin Alcohol", "Precio": 3000, "Activo": true },
  { "id": 125, "Nombre": "Mojito Cubano sin Alcohol 500cc", "Precio": 4500, "Activo": true },
  { "id": 126, "Nombre": "Mojito Sabores sin Alcohol 500cc", "Precio": 4990, "Activo": true },
  { "id": 127, "Nombre": "Trilogía Chilena", "Precio": 19990, "Activo": true },
  { "id": 128, "Nombre": "Papas Fritas (Caseras)", "Precio": 6990, "Activo": true },
  { "id": 129, "Nombre": "Salchipapas", "Precio": 7990, "Activo": true },
  { "id": 130, "Nombre": "Papas Bravas", "Precio": 9990, "Activo": true },
  { "id": 131, "Nombre": "Tabla Picoteo pequeño", "Precio": 4490, "Activo": true },
  { "id": 132, "Nombre": "Tabla Picoteo mediano", "Precio": 8990, "Activo": true },
  { "id": 133, "Nombre": "Ceviche salmón 500 gr", "Precio": 12990, "Activo": true },
  { "id": 134, "Nombre": "Ensalada César", "Precio": 9990, "Activo": true },
  { "id": 135, "Nombre": "Picoteo de camarón", "Precio": 9990, "Activo": true },
  { "id": 136, "Nombre": "Tacos de carnitas 3x", "Precio": 9990, "Activo": true },
  { "id": 137, "Nombre": "Tortillas para untar", "Precio": 3990, "Activo": true },
  { "id": 138, "Nombre": "michemango", "Precio": 6990, "Activo": true },
  { "id": 139, "Nombre": "michecamaron", "Precio": 7590, "Activo": true },
  { "id": 140, "Nombre": "michemexicana", "Precio": 6990, "Activo": true },
  { "id": 141, "Nombre": "piscola", "Precio": 4990, "Activo": true }
]